@include('layouts.site.blocks.header')
@include('layouts.site.blocks.content.why')
@include('layouts.site.blocks.content.aboutus-home')
@include('layouts.site.blocks.content.services-home')
@include('layouts.site.blocks.content.faq-home')
@include('layouts.site.blocks.content.article-home')